# simple one. User defined folder creating in docker image

# Get the latest version of Playwright image
FROM mcr.microsoft.com/playwright:v1.44.0-focal

# Set the work directory for the application.
RUN mkdir /tests
COPY . /tests
WORKDIR /tests

# Install the dependencies in Node environment
RUN npm install
# RUN npx @playwright/test install
# RUN npx playwright install-deps 
# RUN npx playwright test